### ISSUE TITLE
Can you make a higher resolution photo?

### ISSUE THREAD

**Issue by okineadev** [PKief/svg-icon-review#1]
It would be nice if you could take a clearer photo

![](https://camo.githubusercontent.com/9bae7012204dd87948c53f376ea41eb77f55c1e6f27b4d347330bc3cdf51d9ec/68747470733a2f2f69696c692e696f2f4a69706f4f54462e706e67)

**Comment by PKief** [comment]
Which resolution are you thinking of?

**Comment by okineadev** [comment]
2 times larger, because the photo looks blurry

**Comment by PKief** [comment]
If it's blurry then it might be that it's not grid aligned. Please have a look at this issue: https://github.com/PKief/vscode-material-icon-theme/issues/2225. The intention of this image is to give a preview how the icon could look like in a file icon theme as it is used for the Material Icon Theme. I've also adjusted it already in the past to make it more similar to the rendering of VS Code (see https://github.com/PKief/svg-icon-review/commit/81ebc42135161c2d8804be9ffc147b1bc3704bd3). In addition the image is not provided in super high resolution from the image provider itself, but for the preview it's fine for me. And if the bigger image should be 2 times larger it might look odd if there're multiple icons in a list, as it is shown here:

![image](https://github.com/PKief/svg-icon-review/assets/12248527/402a2c0b-14e1-41b7-ac8d-101b0fe5b518)

**Comment by okineadev** [comment]
Got it, thanks

**Comment by okineadev** [comment]
@PKief, In icon-review there is already a link to a preview of the pixel-perfect icon, and I believe that there is no point in making a blurry image

**Comment by PKief** [comment]
@okineadev the idea is to give a preview how does the icon looks in the file explorer of VS Code. It's intentionally that the icon is very small. It demonstrates how the icon looks in very small. If some icons don't look good in a very small size, then it's an indicator that we need to improve that icon. All icons need to be in a good shape to be visible also in small sizes.

**Comment by okineadev** [comment]
Is it possible to make the image clearer in general, but the small icons will be blurred as they are now?

**Comment by PKief** [comment]
We have to figure it out. Probably it's due to the image service we are using for it. It sends the image with a lower quality. If you like you can try to find another image service - which is free to use and provides an API which we can call from a GitHub workflow.

I'm quite busy at the moment, and can live with the current quality of the preview image. As you've said, for getting a better quality image you can click on the pixel perfect link or open the file directly in either GitHub or in VS Code.

**Comment by okineadev** [comment]
Okay

**Comment by okineadev** [comment]
I experimented with this tool and this is what I got:

![image](https://github.com/user-attachments/assets/a4aa3f09-ffb4-4de3-b084-c3c1df4dfe46)

A small image is specially blurred to understand whether it will look good in the editor

**Comment by PKief** [comment]
Closed with #4
